savings-accounts:
  SILVER:
    tierName: '&#828282&lSilver Tier'
    price: 200.0
    interest: 0.05
  GOLD:
    tierName: ''
    price: 10000.0
    interest: 0.50
  PLATINUM:
    tierName: ''
    price: 10000000.0
    interest: 1.0